# Generated by Django 3.0 on 2020-01-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dono', '0002_auto_20200113_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dono',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
    ]
