# Generated by Django 3.0 on 2020-01-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatinho', '0005_auto_20200113_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatinho',
            name='cor',
        ),
        migrations.AddField(
            model_name='gatinho',
            name='cor_do_pelo',
            field=models.CharField(choices=[('MARRON', 'Marron'), ('CINZA', 'Cinza'), ('LARANJA', 'Laranja'), ('BEGE', 'Bege'), ('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('PARDO', 'Pardo')], default='BRANCO', max_length=100),
        ),
    ]
