# Generated by Django 3.0 on 2020-01-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dono', '0003_auto_20200115_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('cor_do_pelo', models.CharField(choices=[('MARRON', 'Marron'), ('CINZA', 'Cinza'), ('LARANJA', 'Laranja'), ('BEGE', 'Bege'), ('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('PARDO', 'Pardo')], default='BRANCO', max_length=100)),
                ('dono', models.ManyToManyField(to='dono.Dono')),
            ],
        ),
    ]
